services:
  backend:
    image: ${BACKEND_IMAGE:-backend:latest}
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/src
      - sqlite_data:/data

    env_file:
      - .env
    command:
      [
        "uvicorn",
        "src.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    tty: true
    stdin_open: true

  frontend:
    image: ${FRONTEND_IMAGE:-frontend:latest}
    build: ./frontend
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src
    command: ["npm", "run", "dev"]
    depends_on:
      - backend

volumes:
  sqlite_data:
